"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { Search, Filter, ShoppingBag } from "lucide-react";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";

export default function ShopPage() {
  // 1. FETCH DATA FROM CONVEX
  const rawProducts = useQuery(api.product.getAllProducts);

  // 2. LOCAL STATE
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [sortBy, setSortBy] = useState("featured");

  // 3. TRANSFORM DATA (Bridge Database -> UI)
  const products = useMemo(() => {
    // Return empty array while loading
    if (!rawProducts) return [];

    return rawProducts.map((p) => {
      // Calculate MRP based on price and discount
      // Formula: Price = MRP - (MRP * Discount / 100)  =>  MRP = Price / (1 - Discount/100)
      const discountDecimal = (p.discount || 0) / 100;
      const mrp = p.discount > 0 
        ? Math.round(p.price / (1 - discountDecimal)) 
        : p.price * 1.2; // random markup if no discount, just for show

      return {
        id: p._id,
        name: p.name,
        // Default category since it's not in DB yet
        category: "Kitchenware", 
        price: p.price,
        mrp: Math.round(mrp),
        discount: p.discount || 0,
        inStock: !p.soldOut, // Database has 'soldOut', UI wants 'inStock'
        code: p._id.slice(-6).toUpperCase(), // Fake a code using ID
        image: p.imageUrl, // URL generated by backend
      };
    });
  }, [rawProducts]);

  // 4. FILTER LOGIC
  const filteredProducts = useMemo(() => {
    return products
      .filter((p) => {
        const matchesSearch = p.name.toLowerCase().includes(search.toLowerCase());
        const matchesCategory = category === "All" || p.category === category;
        return matchesSearch && matchesCategory;
      })
      .sort((a, b) => {
        if (sortBy === "price-low") return a.price - b.price;
        if (sortBy === "price-high") return b.price - a.price;
        return 0; // Default featured (creation order)
      });
  }, [search, category, sortBy, products]);

  // 5. LOADING STATE
  if (rawProducts === undefined) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-pulse flex flex-col items-center">
          <div className="h-12 w-12 bg-gray-300 rounded-full mb-4"></div>
          <p className="text-gray-500">Loading Shop...</p>
        </div>
      </div>
    );
  }

  // 6. RENDER
  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 font-sans">
      {/* HEADER */}
      <header className="bg-white border-b sticky top-0 z-30 p-4 shadow-sm">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row gap-4 items-center justify-between">
          <h1 className="text-2xl font-bold tracking-tight text-red-700 cursor-pointer">
            BOURGON<span className="text-black text-sm ml-2 font-normal">PRIME</span>
          </h1>
          
          {/* SEARCH BAR */}
          <div className="relative w-full md:w-96">
            <Search className="absolute left-3 top-3 text-gray-400" size={18} />
            <input 
              className="w-full bg-gray-100 border-none rounded-full py-2.5 pl-10 pr-4 focus:ring-2 focus:ring-red-600 outline-none transition-shadow"
              placeholder="Search ladles, tongs, cutters..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto py-8 px-4 flex flex-col md:flex-row gap-8">
        
        {/* SIDEBAR FILTERS */}
        <aside className="w-full md:w-64 space-y-6">
          <div>
            <h3 className="font-bold mb-3 flex items-center gap-2 text-gray-800">
              <Filter size={16}/> Categories
            </h3>
            <div className="space-y-1">
              {["All", "Tongs", "Serving", "Cooking", "Kitchenware", "Sets"].map((cat) => (
                <button 
                  key={cat}
                  onClick={() => setCategory(cat)}
                  className={`block w-full text-left px-4 py-2 rounded-lg text-sm transition-colors ${
                    category === cat 
                      ? 'bg-red-50 text-red-700 font-bold' 
                      : 'text-gray-600 hover:bg-gray-100'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        </aside>

        {/* PRODUCT GRID */}
        <main className="flex-1">
          {/* Sorting Header */}
          <div className="flex flex-col sm:flex-row justify-between items-center mb-6 gap-4">
            <p className="text-gray-500 text-sm font-medium">
              Showing {filteredProducts.length} Products
            </p>
            <select 
              className="border border-gray-300 p-2 rounded-lg text-sm bg-white focus:ring-2 focus:ring-red-500 outline-none cursor-pointer"
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value)}
            >
              <option value="featured">Sort by: Featured</option>
              <option value="price-low">Price: Low to High</option>
              <option value="price-high">Price: High to Low</option>
            </select>
          </div>

          {/* EMPTY STATE */}
          {filteredProducts.length === 0 && (
            <div className="text-center py-20 bg-white rounded-xl border border-dashed border-gray-300">
              <p className="text-gray-500">No products found matching your search.</p>
              <button onClick={() => {setSearch(""); setCategory("All")}} className="mt-2 text-red-600 text-sm font-bold hover:underline">
                Clear Filters
              </button>
            </div>
          )}

          {/* GRID */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredProducts.map((product) => (
              <Link href={`/shop/${product.id}`} key={product.id} className="group bg-white rounded-xl border border-gray-200 hover:shadow-xl hover:border-red-100 transition-all duration-300 overflow-hidden relative flex flex-col">
                
                {/* Out of Stock Overlay */}
                {!product.inStock && (
                  <div className="absolute inset-0 bg-white/80 z-20 flex items-center justify-center backdrop-blur-[1px]">
                    <span className="bg-gray-900 text-white px-4 py-2 text-xs font-bold uppercase tracking-wider shadow-lg transform -rotate-6">
                      Out of Stock
                    </span>
                  </div>
                )}

                {/* Discount Badge */}
                {product.inStock && product.discount > 0 && (
                  <div className="absolute top-3 left-3 z-10 bg-red-600 text-white text-[10px] font-bold px-2 py-1 rounded shadow-sm">
                    -{product.discount}% OFF
                  </div>
                )}

                {/* Image Area */}
                <div className="h-64 bg-gray-50 relative overflow-hidden flex items-center justify-center p-6">
                   {product.image ? (
                     <img 
                       src={product.image} 
                       alt={product.name} 
                       className="w-full h-full object-contain mix-blend-multiply group-hover:scale-110 transition-transform duration-500 ease-in-out" 
                     />
                   ) : (
                     // Fallback Placeholder
                     <div className="text-gray-300 font-bold text-6xl select-none opacity-50">
                       {product.name.charAt(0)}
                     </div>
                   )}
                </div>

                {/* Details */}
                <div className="p-5 flex flex-col flex-1">
                  <div className="mb-auto">
                    <p className="text-[10px] text-red-600 font-bold uppercase tracking-wide mb-1">
                      {product.category}
                    </p>
                    <h3 className="font-bold text-lg text-gray-900 leading-tight mb-1 group-hover:text-red-700 transition-colors">
                      {product.name}
                    </h3>
                    <p className="text-xs text-gray-400 font-mono mb-4">
                      #{product.code}
                    </p>
                  </div>
                  
                  <div className="flex items-end justify-between pt-4 border-t border-gray-50">
                    <div>
                      {product.discount > 0 && (
                        <span className="text-xs text-gray-400 line-through mr-2 font-medium">
                          ₹{product.mrp}
                        </span>
                      )}
                      <span className="text-xl font-bold text-gray-900">
                        ₹{product.price}
                      </span>
                    </div>
                    <button 
                      disabled={!product.inStock} 
                      className="bg-black text-white p-2.5 rounded-full hover:bg-red-600 disabled:bg-gray-200 disabled:cursor-not-allowed transition-all shadow-md hover:shadow-lg active:scale-95"
                    >
                      <ShoppingBag size={18} />
                    </button>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}